# Summer Light - alacritty color config
# Originally by Gio Rice (https://github.com/rice7th/summer)
# Light theme Edit by Casper Andersen (https://github.com/ndersorn)

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#f2f2f2'
foreground = '#292a2b'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#ffffff'
cursor = '#4d4d4c'

# Normal colors
[colors.normal]
black = '#1d1f21'
red = '#CF3746'
green = '#7CBD27'
yellow = '#ECBD10'
blue = '#277AB6'
magenta = '#AD4ED2'
cyan = '#32B5C7'
white = '#d8e2e1'

# Bright colors
[colors.bright]
black = '#292A2B'
red = '#d95473'
green = '#b6da74'
yellow = '#e7ca62'
blue = '#64a8d8'
magenta = '#bc82d3'
cyan = '#65cedc'
white = '#ebf6f5'
